### ISSUE TITLE
大佬。seata-server启动的时候报错

### ISSUE THREAD

**Issue by arraycto** [lidong1665/springboot-dubbo-seata-nacos#3]
seata1.2.0
nacos：1.1.4 

配置已经按照大佬的方式，进入了nacos。

随后启动seata报错，启动命令

./seata-server.sh  -p 8091 -h 127.0.0.1  -m db

log如下

```

15:27:39,985 |-INFO in ch.qos.logback.core.joran.action.AppenderRefAction - Attaching appender named [stdout] to Logger[ROOT]
15:27:39,985 |-INFO in ch.qos.logback.classic.joran.action.ConfigurationAction - End of configuration.
15:27:39,985 |-INFO in ch.qos.logback.classic.joran.JoranConfigurator@6cc4c815 - Registering current configuration as safe fallback point

2020-07-01 15:27:40.174 INFO [main]io.seata.config.FileConfiguration.<init>:121 -The configuration file used is registry.conf
2020-07-01 15:27:40.754 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.file.session.FileSessionManager has already been loaded, skipped
2020-07-01 15:27:40.755 WARN [main]i.s.c.l.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadFile:482 -The same extension io.seata.server.storage.db.session.DataBaseSessionManager has already been loaded, skipped
Exception in thread "main" io.seata.common.loader.EnhancedServiceNotFoundException: not found service provider for : io.seata.server.session.SessionManager caused by java.lang.IllegalStateException: Extension instanition: io.seata.common.loader.ExtensionDefinition@218540c9, class: interface io.seata.server.session.SessionManager)  could not be instantiated: the name of service provider for [io.seata.core.store.db.DataSourceGenname is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:404)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.getExtensionInstance(EnhancedServiceLoader.java:393)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:358)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.session.SessionHolder.init(SessionHolder.java:87)
	at io.seata.server.Server.main(Server.java:75)
Caused by: java.lang.IllegalArgumentException: the name of service provider for [io.seata.core.store.db.DataSourceGenerator] name is null
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.loadExtension(EnhancedServiceLoader.java:353)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.load(EnhancedServiceLoader.java:247)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.access$200(EnhancedServiceLoader.java:188)
	at io.seata.common.loader.EnhancedServiceLoader.load(EnhancedServiceLoader.java:80)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.<init>(DataBaseTransactionStoreManager.java:98)
	at io.seata.server.storage.db.store.DataBaseTransactionStoreManager.getInstance(DataBaseTransactionStoreManager.java:84)
	at io.seata.server.storage.db.session.DataBaseSessionManager.init(DataBaseSessionManager.java:81)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.initInstance(EnhancedServiceLoader.java:560)
	at io.seata.common.loader.EnhancedServiceLoader$InnerEnhancedServiceLoader.createNewExtension(EnhancedServiceLoader.java:400)
	... 7 more

[root@iZ8vbido9l61vd7k054mitZ bin]# ps -ef|grep seata
root     25274  8073  0 15:28 pts/1    00:00:00 grep --color=auto seata
[root@iZ8vbido9l61vd7k054mitZ bin]# 

```

**Comment by arraycto** [comment]
烦请大佬指点一下思路，搞了好久，无果
